"""Strict worker-protocol foundation.

These helpers implement transport integrity and closed identities. They do not
fit an EBM, infer scientific truth, or accept a backend.
"""

from __future__ import annotations

from .bundle import (
    build_files_map,
    capture_bundle_snapshot,
    exact_file_sha256_path,
    read_regular_file_exact,
    verify_files_map,
    verify_snapshot_unchanged,
)
from .canonical import (
    canonical_json_bytes,
    domain_separated_bytes_sha256,
    exact_file_sha256,
    strict_json_loads,
    structured_sha256,
    structured_sha256_hex,
)
from .errors import (
    BundleValidationError,
    CanonicalizationError,
    FramingError,
    PathBoundaryError,
    ProtocolError,
)
from .framing import (
    load_worker_request,
    load_worker_response,
    write_worker_request,
    write_worker_response,
)
from .identities import (
    actual_fit_worker_subject_digest,
    actual_stage_worker_subject_digest,
    actual_validate_worker_subject_digest,
    adapter_semantics_digest,
    audit_case_configuration_digest,
    authenticated_execution_evidence_digest,
    authenticated_request_evidence_digest,
    backend_identity_digest,
    bind_request_digests,
    bind_response_metadata_digest,
    capabilities_digest,
    core_observed_failure_digest,
    deterministic_fit_request_id,
    execution_input_projection_digest,
    expected_identity_pin,
    expected_identity_pin_digest,
    request_metadata_digest,
    requested_output_registry_digest,
    requested_outputs_digest,
    response_metadata_digest,
    retry_equivalence_digest,
    retry_equivalence_projection,
    scientific_request_digest,
    scientific_request_projection,
    scientific_requested_outputs_digest,
    selected_algorithm_binding_digest,
    self_test_check_registry_digest,
    settings_digest,
    settings_schema_digest,
    stage_semantics_digest,
    validate_execution_input_projection,
    validate_expected_identity_pin,
    validate_request_execution_input_binding,
    validate_result_record_finalization,
    worker_command_evidence_digest,
    worker_fit_payload_digest,
    worker_stage_result_digest,
    worker_validation_payload_digest,
)
from .models import (
    BundleSnapshot,
    FileRecord,
    WorkerCommand,
    WorkerRequestFrame,
    WorkerResponseFrame,
    WorkerStatus,
)
from .paths import ensure_private_directory, resolve_contained_path, validate_relative_posix_path

__all__ = [
    "BundleSnapshot",
    "BundleValidationError",
    "CanonicalizationError",
    "FileRecord",
    "FramingError",
    "PathBoundaryError",
    "ProtocolError",
    "WorkerCommand",
    "WorkerRequestFrame",
    "WorkerResponseFrame",
    "WorkerStatus",
    "actual_fit_worker_subject_digest",
    "actual_stage_worker_subject_digest",
    "actual_validate_worker_subject_digest",
    "adapter_semantics_digest",
    "audit_case_configuration_digest",
    "authenticated_execution_evidence_digest",
    "authenticated_request_evidence_digest",
    "backend_identity_digest",
    "bind_request_digests",
    "bind_response_metadata_digest",
    "build_files_map",
    "canonical_json_bytes",
    "capabilities_digest",
    "capture_bundle_snapshot",
    "core_observed_failure_digest",
    "deterministic_fit_request_id",
    "domain_separated_bytes_sha256",
    "ensure_private_directory",
    "exact_file_sha256",
    "exact_file_sha256_path",
    "execution_input_projection_digest",
    "expected_identity_pin",
    "expected_identity_pin_digest",
    "load_worker_request",
    "load_worker_response",
    "read_regular_file_exact",
    "request_metadata_digest",
    "requested_output_registry_digest",
    "requested_outputs_digest",
    "resolve_contained_path",
    "response_metadata_digest",
    "retry_equivalence_digest",
    "retry_equivalence_projection",
    "scientific_request_digest",
    "scientific_request_projection",
    "scientific_requested_outputs_digest",
    "selected_algorithm_binding_digest",
    "self_test_check_registry_digest",
    "settings_digest",
    "settings_schema_digest",
    "stage_semantics_digest",
    "strict_json_loads",
    "structured_sha256",
    "structured_sha256_hex",
    "validate_execution_input_projection",
    "validate_expected_identity_pin",
    "validate_relative_posix_path",
    "validate_request_execution_input_binding",
    "validate_result_record_finalization",
    "verify_files_map",
    "verify_snapshot_unchanged",
    "worker_command_evidence_digest",
    "worker_fit_payload_digest",
    "worker_stage_result_digest",
    "worker_validation_payload_digest",
    "write_worker_request",
    "write_worker_response",
]
