#!/usr/bin/env python3
"""Local worker entry point generated by ``ebm-audit adapter init``."""

from __future__ import annotations

from pathlib import Path

from synthetic_example import SyntheticProtocolExampleBackend  # type: ignore[import-not-found]

from ebm_audit.worker_sdk import (
    WorkerApplication,
    build_synthetic_protocol_identity,
)


def main() -> int:
    identity = build_synthetic_protocol_identity(
        adapter_id="generated-synthetic-only-adapter",
        backend_name="generated-synthetic-only-protocol-example",
        code_paths=[
            Path(__file__).resolve(),
            Path(__file__).with_name("synthetic_example.py"),
        ],
    )
    return WorkerApplication(SyntheticProtocolExampleBackend(identity)).run()


if __name__ == "__main__":
    raise SystemExit(main())
